📝 Update CLI command docs
jovotech/jovo-cli pull request #275
Opened 2021-12-13 17:18 UTC by jankoenig

This PR adds a note about the `bundle` scripts and also fixes some links

2021-12-14 14:04 UTC, rubenaeg requested changes

2021-12-14 14:04 UTC, rubenaeg commented on docs/deploy-command.md
> +- [`deploy:code`](#deploy-platform): Upload the source code to a cloud provider (e.g. AWS Lambda)
I think that should be `#deploy-code`, right?

2021-12-14 14:04 UTC, rubenaeg commented on docs/deploy-command.md
> +Jovo uses [`esbuild`](https://github.com/evanw/esbuild) for fast bundling and small file sizes. Depending on the stage, the `deploy:code` command executes the `bundle` (if no stage is used) or `bundl
Currently, the Serverless integration uses `dev` as the default stage, since the standalone `bundle` script doesn't specify an index file.

2021-12-15 15:14 UTC, jankoenig commented on docs/deploy-command.md
> +- [`deploy:code`](#deploy-platform): Upload the source code to a cloud provider (e.g. AWS Lambda)
good catch! thank you

2021-12-15 15:15 UTC, jankoenig commented on docs/deploy-command.md
> +Jovo uses [`esbuild`](https://github.com/evanw/esbuild) for fast bundling and small file sizes. Depending on the stage, the `deploy:code` command executes the `bundle` (if no stage is used) or `bundl
Thanks!

2021-12-15 15:15 UTC, merged